macro(GENERATE FILENAME OUTPUTDIR)
	file(MAKE_DIRECTORY ${OUTPUTDIR})
	if(NOT DEFINED THRIFT_COMPILER)
		find_program(THRIFT_COMPILER thrift)
		if(NOT THRIFT_COMPILER)
			message(FATAL_ERROR "Thrift compiler not found")
    	endif()
	endif()
	execute_process(COMMAND ${THRIFT_COMPILER} --gen cpp:no_skeleton -out ${OUTPUTDIR} ${FILENAME}
					RESULT_VARIABLE CMD_RESULT)
	if(CMD_RESULT)
		message(FATAL_ERROR "Error generating ${FILENAME} with generator ${GENERATOR}")
	endif()
	get_filename_component(IDL_NAME ${FILENAME} NAME_WE)
	file(GLOB_RECURSE GENERATED_SOURCES ${OUTPUTDIR}/*.cpp)
	add_library(${IDL_NAME} STATIC ${GENERATED_SOURCES})
	set_target_properties(${IDL_NAME} PROPERTIES POSITION_INDEPENDENT_CODE ON)
	target_link_libraries(${IDL_NAME} ${THRIFT_LIBRARIES})
	include_directories(${OUTPUTDIR})
endmacro(GENERATE)
