name: ci

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - '3rdparty/include/**'
      - 'include/**'
      - 'source/**'
      - 'sample/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '*.sln'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '3rdparty/include/**'
      - 'include/**'
      - 'source/**'
      - 'sample/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '*.sln'
  workflow_dispatch:

jobs:

  windows:
    strategy:
      matrix:
        include:
          - msbuild_target: x64
            lowercase_target: x64
          - msbuild_target: ARM64
            lowercase_target: arm64
    env:
      MAABUILDER_TARGET_PLATFORM: ${{ matrix.msbuild_target }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap MaaDeps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 maadeps-download.py ${{ matrix.lowercase_target }}-windows

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Build MaaSample
        run: |
          MSBUILD MAA.sln /t:rebuild /p:Configuration="Release" /p:Platform="${{ matrix.msbuild_target }}" /m

      - uses: actions/upload-artifact@v3
        with:
          name: MAA-win-${{ matrix.lowercase_target }}
          path: ${{ matrix.msbuild_target }}/Release

  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3

      - name: Install cmake
        run: |
          pacman -Sy
          pacman -S --noconfirm cmake

      - name: Install cross compile toolchains
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          pacman -Sy
          pacman -S --noconfirm aarch64-linux-gnu-gcc

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          remove_stale_cache: false

      - name: Bootstrap MaaDeps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 maadeps-download.py ${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}-linux

      - name: Build MAA
        env:
          CC: ${{ matrix.arch == 'x86_64' && 'ccache gcc' || 'ccache aarch64-linux-gnu-gcc' }}
          CXX: ${{ matrix.arch == 'x86_64' && 'ccache g++' || 'ccache aarch64-linux-gnu-g++' }}
        run: |
          mkdir -p build
          cmake -B build \
            -DMAADEPS_TRIPLET='maa-${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}-linux' \
            -DINSTALL_THIRD_LIBS=ON \
            -DINSTALL_RESOURCE=ON \
            -DINSTALL_PYTHON=ON \
            -DMAA_VERSION='${{ needs.meta.outputs.tag }}'
          cmake --build build --parallel $(nproc --all)

          mkdir -p install
          cmake --install build --prefix install

      - uses: actions/upload-artifact@v3
        with:
          name: MAA-linux-${{ matrix.arch }}
          path: 'install'

  # macOS:
  #   runs-on: macos-13
  #   strategy:
  #     matrix:
  #       arch: [arm64, x86_64]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install Dependencies
  #       run: brew install ninja
  #     - name: Bootstrap MaaDeps
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: |
  #         [[ ${{ matrix.arch }} = "arm64" ]] && triplet="arm64-osx" || triplet="x64-osx"
  #         python3 maadeps-download.py ${triplet}
  #     - name: Configure MaaFramework
  #       run: |
  #         cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES='${{ matrix.arch }}' -DMAA_VERSION='${{ needs.meta.outputs.tag }}'
  #     - name: Build MaaFramework
  #       run: |
  #         cmake --build build
  #         cmake --install build --prefix install
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: MaaFramework-macos-${{ matrix.arch }}
  #         path: 'install/*.dylib'
